name: Build and Deploy Code

on: [push, pull_request]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: pullking git repo
              uses: actions/checkout@v2
            - name: say hi to me
              run: echo "say hi to me"
              